#!/usr/bin/env python3
"""Deployment key and the WPA2 credentials of a node's maintenance access point.

Commands:
  keygen --out deploy.key              new 32-byte deployment key (hex, mode 0600, never
                                       overwritten). Load it on each node with /key.set <hex>
  show --key-file deploy.key --node 1A2B
                                       prints the key fingerprint (as /key shows it on a node),
                                       the AP name, its password and the WiFi QR text
  vectors                              regenerates test/vectors/apPassVectors.h

A node with mesh address 0x1A2B opens the AP "LM-1A2B". Its password is
hex(HMAC-SHA256(K, "LMAP1" || address u16 LE)[:8]): 16 lowercase hex characters, the same
derivation as lib/OtaCrypto/src/deploymentKey.cpp. Standard library only.
"""
import argparse
import hashlib
import hmac
import os
import secrets
import struct
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[2]
VECTORS_DIR = ROOT / "test" / "vectors"
KEY_SIZE = 32
AP_LABEL = b"LMAP1"
AP_PASSWORD_BYTES = 8
# Test vectors only: a fixed, public key.
VECTOR_KEY = bytes(range(KEY_SIZE))
VECTOR_NODES = (0x0000, 0x000C, 0x1A2B, 0x7680, 0xFFFF)


class KeyFileError(Exception):
    pass


def ap_password(key: bytes, node: int) -> str:
    digest = hmac.new(key, AP_LABEL + struct.pack("<H", node), hashlib.sha256).digest()
    return digest[:AP_PASSWORD_BYTES].hex()


def key_fingerprint(key: bytes) -> str:
    return hashlib.sha256(key).digest()[:4].hex()


def ap_ssid(node: int) -> str:
    return f"LM-{node:04X}"


def wifi_qr(key: bytes, node: int) -> str:
    return f"WIFI:T:WPA;S:{ap_ssid(node)};P:{ap_password(key, node)};;"


def parse_node(text: str) -> int:
    digits = text[2:] if text.lower().startswith("0x") else text
    try:
        node = int(digits, 16)
    except ValueError:
        raise KeyFileError(f"node address {text!r} is not hexadecimal") from None
    if not digits or len(digits) > 4 or node > 0xFFFF:
        raise KeyFileError(f"node address {text!r} is not a 16-bit address")
    return node


def load_key(path: Path) -> bytes:
    text = Path(path).read_text().strip()
    try:
        key = bytes.fromhex(text)
    except ValueError:
        raise KeyFileError(f"{path} is not hexadecimal") from None
    if len(key) != KEY_SIZE:
        raise KeyFileError(f"{path} holds {len(key)} bytes, expected {KEY_SIZE}")
    return key


def keygen(out: Path) -> bytes:
    key = secrets.token_bytes(KEY_SIZE)
    try:
        fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        raise KeyFileError(f"{out} already exists") from None
    with os.fdopen(fd, "w") as f:
        f.write(key.hex() + "\n")
    return key


def vectors_header() -> str:
    lines = [
        "// Generated by scripts/ota_tools/ap_pass.py vectors. Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "static const uint8_t AP_VECTOR_KEY[32] = {"
        + ", ".join(f"0x{b:02X}" for b in VECTOR_KEY) + "};",
        "",
        f'static const char* AP_VECTOR_KEY_FINGERPRINT = "{key_fingerprint(VECTOR_KEY)}";',
        "",
        "struct ApPassVector {",
        "    uint16_t node;",
        "    const char* ssid;",
        "    const char* password;",
        "};",
        "",
        "static const ApPassVector AP_PASS_VECTORS[] = {",
    ]
    for node in VECTOR_NODES:
        lines.append(f'    {{0x{node:04X}, "{ap_ssid(node)}", "{ap_password(VECTOR_KEY, node)}"}},')
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("keygen")
    gen.add_argument("--out", type=Path, required=True)
    show = sub.add_parser("show")
    show.add_argument("--key-file", type=Path, required=True)
    show.add_argument("--node", required=True, help="mesh address in hex, e.g. 1A2B")
    vec = sub.add_parser("vectors")
    vec.add_argument("--out", type=Path, default=VECTORS_DIR / "apPassVectors.h")
    args = parser.parse_args(argv)

    try:
        if args.command == "keygen":
            keygen(args.out)
            print(f"Deployment key written to {args.out}. Keep it offline; load it on each "
                  f"node with /key.set (the hex in the file).")
        elif args.command == "show":
            key = load_key(args.key_file)
            node = parse_node(args.node)
            print(f"key:      fingerprint {key_fingerprint(key)}")
            print(f"ssid:     {ap_ssid(node)}")
            print(f"password: {ap_password(key, node)}")
            print(f"qr:       {wifi_qr(key, node)}")
        else:
            args.out.write_text(vectors_header())
            print(f"Wrote {args.out}")
    except KeyFileError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
