#!/usr/bin/env python3
"""Signs commands for LoRaChat nodes with the deployment key.

Commands:
  sign --key-file deploy.key --node 7680 "/maint.open 600 ap"
        prints the signed line to type on a gateway's serial console:
        "@7680 /maint.open 600 ap #<counter>.<tag>"; with --mqtt <request id> the payload for
        the gateway's MQTT topic cmd/<gateway>: "7680 <request id> /maint.open ... #<sig>"
  wifi --key-file deploy.key --node 7680 --ssid NAME
        asks for the password (not echoed) and prints the signed /maint.wifi line; the SSID and
        password are encrypted for that node and that counter
  vectors
        regenerates test/vectors/cmdVectors.h for the native tests

Tag: HMAC-SHA256(K, "LMC1" || dst u16 LE || counter u32 LE || line)[:8], as
lib/CmdCore/src/cmdAuth.cpp. Counter: max(last + 1, unix time), remembered per key in
--state, so a laptop and a phone can sign with the same key without sharing state.
Encrypted arguments: XOR with blocks HMAC-SHA256(Kw, dst || counter || i), Kw = HMAC(K, "LMW1")
(lib/CmdCore/src/cmdSeal.cpp). Standard library only.
"""
import argparse
import getpass
import hashlib
import hmac
import json
import struct
import sys
import time
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

import ap_pass  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
VECTORS_DIR = ROOT / "test" / "vectors"
DEFAULT_STATE = Path.home() / ".config" / "loramesher" / "command_counters.json"
AUTH_LABEL = b"LMC1"
SEAL_LABEL = b"LMW1"
TAG_SIZE = 8
MAX_SSID = 32
MIN_PASSWORD, MAX_PASSWORD = 8, 63
VECTOR_KEY = bytes(range(32))


class CommandError(Exception):
    pass


def auth_message(dst: int, counter: int, line: str) -> bytes:
    return AUTH_LABEL + struct.pack("<HI", dst, counter) + line.encode()


def command_tag(key: bytes, dst: int, counter: int, line: str) -> bytes:
    return hmac.new(key, auth_message(dst, counter, line), hashlib.sha256).digest()[:TAG_SIZE]


def format_signature(counter: int, tag: bytes) -> str:
    return f" #{counter:08x}.{tag.hex()}"


def signed_line(key: bytes, dst: int, counter: int, line: str) -> str:
    return f"@{dst:04X} {line}{format_signature(counter, command_tag(key, dst, counter, line))}"


def mqtt_payload(key: bytes, dst: int, counter: int, request_id: int, line: str) -> str:
    """Payload for the gateway's cmd/<gateway> topic."""
    signature = format_signature(counter, command_tag(key, dst, counter, line))
    return f"{dst:04X} {request_id} {line}{signature}"


def seal_args(key: bytes, dst: int, counter: int, data: bytes) -> bytes:
    seal_key = hmac.new(key, SEAL_LABEL, hashlib.sha256).digest()
    stream = b""
    block = 0
    while len(stream) < len(data):
        stream += hmac.new(seal_key, struct.pack("<HIB", dst, counter, block),
                           hashlib.sha256).digest()
        block += 1
    return bytes(a ^ b for a, b in zip(data, stream))


def wifi_line(key: bytes, dst: int, counter: int, ssid: str, password: str) -> str:
    raw_ssid, raw_password = ssid.encode(), password.encode()
    if not 1 <= len(raw_ssid) <= MAX_SSID:
        raise CommandError(f"the SSID must have 1-{MAX_SSID} bytes")
    if raw_password and not MIN_PASSWORD <= len(raw_password) <= MAX_PASSWORD:
        raise CommandError(f"a WPA2 password has {MIN_PASSWORD}-{MAX_PASSWORD} characters")
    sealed = seal_args(key, dst, counter, raw_ssid + b"\0" + raw_password)
    return f"/maint.wifi {sealed.hex()}"


def key_id(key: bytes) -> str:
    return ap_pass.key_fingerprint(key)


def next_counter(state: Path, key: bytes, now: Optional[float] = None) -> int:
    counters = json.loads(state.read_text()) if state.exists() else {}
    last = counters.get(key_id(key), 0)
    counter = max(last + 1, int(time.time() if now is None else now))
    counters[key_id(key)] = counter
    state.parent.mkdir(parents=True, exist_ok=True)
    state.write_text(json.dumps(counters))
    return counter


def vectors_header() -> str:
    tags = [(0x7680, 1, "/reboot"), (0x1A2B, 0x65000000, "/maint.open 600 ap"),
            (0x0000, 0xFFFFFFFF, "/version")]
    seal_plain = bytes(range(40))
    wifi = (0x7680, 9, "BenchNet", "password123")
    lines = [
        "// Generated by scripts/ota_tools/lmcmd.py vectors. Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "static const uint8_t CMD_VECTOR_KEY[32] = {",
        "    " + ", ".join(f"0x{b:02X}" for b in VECTOR_KEY[:16]) + ",",
        "    " + ", ".join(f"0x{b:02X}" for b in VECTOR_KEY[16:]) + "};",
        "",
        "struct CmdTagVector {",
        "    uint16_t dst;",
        "    uint32_t counter;",
        "    const char* line;",
        "    const char* tag;",
        "    const char* serial;",
        "};",
        "",
        "static const CmdTagVector CMD_TAG_VECTORS[] = {",
    ]
    for dst, counter, line in tags:
        tag = command_tag(VECTOR_KEY, dst, counter, line).hex()
        serial = signed_line(VECTOR_KEY, dst, counter, line)
        lines.append(f'    {{0x{dst:04X}, 0x{counter:08X}, "{line}", "{tag}", "{serial}"}},')
    lines += [
        "};",
        "",
        f"static const uint16_t CMD_SEAL_DST = 0x{0x7680:04X};",
        "static const uint32_t CMD_SEAL_COUNTER = 9;",
        f'static const char* CMD_SEAL_PLAIN = "{seal_plain.hex()}";',
        f'static const char* CMD_SEAL_SEALED = "{seal_args(VECTOR_KEY, 0x7680, 9, seal_plain).hex()}";',
        "",
        f'static const char* CMD_WIFI_SSID = "{wifi[2]}";',
        f'static const char* CMD_WIFI_PASSWORD = "{wifi[3]}";',
        f'static const char* CMD_WIFI_LINE = "{wifi_line(VECTOR_KEY, *wifi)}";',
        "",
    ]
    return "\n".join(lines)


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("sign", "wifi"):
        p = sub.add_parser(name)
        p.add_argument("--key-file", type=Path, required=True)
        p.add_argument("--node", required=True, help="mesh address in hex, e.g. 7680")
        p.add_argument("--state", type=Path, default=DEFAULT_STATE)
        p.add_argument("--mqtt", type=int, metavar="REQUEST_ID",
                       help="print the payload for the gateway's cmd/<gateway> MQTT topic")
        if name == "sign":
            p.add_argument("line", help='command line, e.g. "/maint.open 600 ap"')
        else:
            p.add_argument("--ssid", required=True)
    vec = sub.add_parser("vectors")
    vec.add_argument("--out", type=Path, default=VECTORS_DIR / "cmdVectors.h")
    args = parser.parse_args(argv)

    try:
        if args.command == "vectors":
            args.out.write_text(vectors_header())
            print(f"Wrote {args.out}")
            return 0
        key = ap_pass.load_key(args.key_file)
        node = ap_pass.parse_node(args.node)
        counter = next_counter(args.state, key)
        if args.command == "sign":
            line = args.line
        else:
            password = getpass.getpass(f"Password for {args.ssid} (empty for an open network): ")
            line = wifi_line(key, node, counter, args.ssid, password)
        if args.mqtt is not None:
            print(mqtt_payload(key, node, counter, args.mqtt, line))
        else:
            print(signed_line(key, node, counter, line))
    except (CommandError, ap_pass.KeyFileError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
