#!/usr/bin/env python3
"""Node report signature: test vectors and the report key.

Commands:
  header                    regenerates test/vectors/reportVectors.h from
                            test/vectors/report_vectors.json
  key --key-file deploy.key prints the report key Kr for the server's OTA_REPORT_KEY

A node signs the raw body of POST /report with Kr = HMAC-SHA256(K, "LMR1"), K being the
deployment key, and sends hex(HMAC-SHA256(Kr, body)) in the X-LM-Tag header. The server only
holds Kr. report_vectors.json is generated by LoRaMesherWeb ota/vectors/make_vectors.py and
copied here unchanged. Standard library only.
"""
import argparse
import hashlib
import hmac
import json
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[2]
VECTORS_JSON = ROOT / "test" / "vectors" / "report_vectors.json"
VECTORS_HEADER = ROOT / "test" / "vectors" / "reportVectors.h"
REPORT_LABEL = b"LMR1"


def report_key(deployment_key: bytes) -> bytes:
    return hmac.new(deployment_key, REPORT_LABEL, hashlib.sha256).digest()


def c_bytes(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02X}" for b in data) + "}"


def c_string(text: str) -> str:
    return json.dumps(text)


def vectors_header(vectors: dict) -> str:
    lines = [
        "// Generated by scripts/ota_tools/report_vectors.py header. Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "static const uint8_t REPORT_VECTOR_KEY[32] = "
        + c_bytes(bytes.fromhex(vectors["deployment_key"])) + ";",
        "static const uint8_t REPORT_VECTOR_REPORT_KEY[32] = "
        + c_bytes(bytes.fromhex(vectors["report_key"])) + ";",
        "",
        "struct ReportVector {",
        "    const char* name;",
        "    const char* body;",
        "    const char* tag;",
        "    bool valid;",
        "};",
        "",
        "static const ReportVector REPORT_VECTORS[] = {",
    ]
    for case in vectors["cases"]:
        lines.append(f"    {{{c_string(case['name'])}, {c_string(case['body'])}, "
                     f"{c_string(case['tag'])}, {'true' if case['valid'] else 'false'}}},")
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    head = sub.add_parser("header")
    head.add_argument("--json", type=Path, default=VECTORS_JSON)
    head.add_argument("--out", type=Path, default=VECTORS_HEADER)
    key = sub.add_parser("key")
    key.add_argument("--key-file", type=Path, required=True)
    args = parser.parse_args(argv)

    if args.command == "header":
        args.out.write_text(vectors_header(json.loads(args.json.read_text())))
        print(f"wrote {args.out}")
    else:
        deployment_key = bytes.fromhex(args.key_file.read_text().strip())
        if len(deployment_key) != 32:
            print("report_vectors: the key file must hold 64 hex digits", file=sys.stderr)
            return 1
        print(report_key(deployment_key).hex())
    return 0


if __name__ == "__main__":
    sys.exit(main())
