// Generated by scripts/ota_tools/ap_pass.py vectors. Do not edit.
#pragma once

#include <cstdint>

static const uint8_t AP_VECTOR_KEY[32] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F};

static const char* AP_VECTOR_KEY_FINGERPRINT = "630dcd29";

struct ApPassVector {
    uint16_t node;
    const char* ssid;
    const char* password;
};

static const ApPassVector AP_PASS_VECTORS[] = {
    {0x0000, "LM-0000", "ebf5e3cc7778f9c0"},
    {0x000C, "LM-000C", "bf0e54d0b4d2efe0"},
    {0x1A2B, "LM-1A2B", "6fed5935a38b2310"},
    {0x7680, "LM-7680", "f089b88d4b134b6e"},
    {0xFFFF, "LM-FFFF", "6590e6aa360d4464"},
};
