// Generated by scripts/ota_tools/lmcmd.py vectors. Do not edit.
#pragma once

#include <cstdint>

static const uint8_t CMD_VECTOR_KEY[32] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F};

struct CmdTagVector {
    uint16_t dst;
    uint32_t counter;
    const char* line;
    const char* tag;
    const char* serial;
};

static const CmdTagVector CMD_TAG_VECTORS[] = {
    {0x7680, 0x00000001, "/reboot", "d15620d50289ed6f", "@7680 /reboot #00000001.d15620d50289ed6f"},
    {0x1A2B, 0x65000000, "/maint.open 600 ap", "48fbaa33fa0d63c5", "@1A2B /maint.open 600 ap #65000000.48fbaa33fa0d63c5"},
    {0x0000, 0xFFFFFFFF, "/version", "7d7606514fdecc01", "@0000 /version #ffffffff.7d7606514fdecc01"},
};

static const uint16_t CMD_SEAL_DST = 0x7680;
static const uint32_t CMD_SEAL_COUNTER = 9;
static const char* CMD_SEAL_PLAIN = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f2021222324252627";
static const char* CMD_SEAL_SEALED = "212fba23e32b4435b2109309fd00ff5545002b8f263b34b56a10481ac0d243cdf5537c5aea62d6e3";

static const char* CMD_WIFI_SSID = "BenchNet";
static const char* CMD_WIFI_PASSWORD = "password123";
static const char* CMD_WIFI_LINE = "/maint.wifi 634bd6438f602746ba69f871827a9e2831200baf";
