// Generated by scripts/ota_tools/report_vectors.py header. Do not edit.
#pragma once

#include <cstdint>

static const uint8_t REPORT_VECTOR_KEY[32] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F};
static const uint8_t REPORT_VECTOR_REPORT_KEY[32] = {0xB4, 0x47, 0xF6, 0x30, 0xD7, 0x5B, 0x08, 0x39, 0x05, 0x82, 0x89, 0x65, 0xF9, 0xB7, 0x4E, 0xE1, 0x34, 0xB8, 0xE1, 0x5B, 0xF3, 0xA8, 0xE2, 0xC5, 0xBB, 0xC9, 0xB1, 0x03, 0x28, 0xFD, 0x14, 0x8F};

struct ReportVector {
    const char* name;
    const char* body;
    const char* tag;
    bool valid;
};

static const ReportVector REPORT_VECTORS[] = {
    {"noop", "{\"v\":1,\"node\":\"7680\",\"mac\":\"08:3a:f2:aa:bb:cc\",\"env\":\"tbeam\",\"role\":\"sensor\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app0\",\"state\":\"VALID\",\"boot\":12,\"rr\":\"POWERON\",\"bl\":\"f43854\",\"event\":\"noop\",\"decision\":1,\"rssi\":-77,\"heap_free\":213000,\"heap_min\":202000,\"batt_mv\":4110,\"vbus\":true,\"uptime_s\":9}", "da84a501129851ee0fbac72b7dd859b9e91f55be5f8bc5532089bf2d5e190485", true},
    {"written", "{\"v\":1,\"node\":\"7680\",\"env\":\"tbeam\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app0\",\"state\":\"VALID\",\"boot\":12,\"event\":\"written\",\"status\":0,\"sha\":\"3fa2c1d4e5f60718\",\"rssi\":-79,\"dl_ms\":23600,\"bytes\":1212336}", "359823de33c54f72ab4d273590a3504b72f675a9bc2c1ea6345efbcd941efcf3", true},
    {"rollback", "{\"v\":1,\"node\":\"5E9C\",\"env\":\"tbeam\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app1\",\"state\":\"VALID\",\"boot\":4,\"rr\":\"SW\",\"event\":\"rollback\",\"last_invalid\":\"app0\",\"reason\":5,\"sha\":\"0011223344556677\"}", "0fb7cc65e3cb4dc61a563db05f8d663046f5acc25333ea0cf470361810fee372", true},
    {"tampered_body", "{\"v\":1,\"node\":\"7680\",\"mac\":\"08:3a:f2:aa:bb:cc\",\"env\":\"tbeam\",\"role\":\"sensor\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app0\",\"state\":\"VALID\",\"boot\":13,\"rr\":\"POWERON\",\"bl\":\"f43854\",\"event\":\"noop\",\"decision\":1,\"rssi\":-77,\"heap_free\":213000,\"heap_min\":202000,\"batt_mv\":4110,\"vbus\":true,\"uptime_s\":9}", "da84a501129851ee0fbac72b7dd859b9e91f55be5f8bc5532089bf2d5e190485", false},
    {"short_tag", "{\"v\":1,\"node\":\"7680\",\"mac\":\"08:3a:f2:aa:bb:cc\",\"env\":\"tbeam\",\"role\":\"sensor\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app0\",\"state\":\"VALID\",\"boot\":12,\"rr\":\"POWERON\",\"bl\":\"f43854\",\"event\":\"noop\",\"decision\":1,\"rssi\":-77,\"heap_free\":213000,\"heap_min\":202000,\"batt_mv\":4110,\"vbus\":true,\"uptime_s\":9}", "da84a501129851ee", false},
    {"wrong_key", "{\"v\":1,\"node\":\"7680\",\"mac\":\"08:3a:f2:aa:bb:cc\",\"env\":\"tbeam\",\"role\":\"sensor\",\"ver\":\"0.1.0+g4434b51\",\"part\":\"app0\",\"state\":\"VALID\",\"boot\":12,\"rr\":\"POWERON\",\"bl\":\"f43854\",\"event\":\"noop\",\"decision\":1,\"rssi\":-77,\"heap_free\":213000,\"heap_min\":202000,\"batt_mv\":4110,\"vbus\":true,\"uptime_s\":9}", "76c432643986126fd195250ead9f1ffc872357af6492609e5113af01feb3f566", false},
};
