"""Load batch YAMLs and materialize per-run experiment YAMLs.

A batch describes an experiment campaign: one or more *cells* (each cell is
one experimental condition) run multiple times. For each (cell, repetition)
the runner materializes a complete per-device experiment YAML that the
existing `configtool` can render into `change-config-*.sh` scripts.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class Cell:
    id: str
    overrides: dict[str, Any] = field(default_factory=dict)
    inactive_devices: tuple[str, ...] = ()
    # Per-cell timing overrides. None means "fall back to batch defaults".
    duration_min: float | None = None
    warmup_min: float | None = None
    cooldown_min: float | None = None


@dataclass(frozen=True)
class Batch:
    name: str
    description: str
    base_yaml: Path
    runs: int
    duration_min: float
    warmup_min: float
    cooldown_min: float
    reset_between_runs: bool
    upload_between_cells: bool
    cells: tuple[Cell, ...]
    warmup_run: bool = False
    boot_verify_sec: int = 20


def load_batch(path: Path) -> Batch:
    """Parse a batch YAML into a frozen Batch dataclass."""
    with path.open() as f:
        raw = yaml.safe_load(f)

    name = raw.get("batch") or path.stem
    description = raw.get("description", "")

    base = raw.get("base")
    if not base:
        raise ValueError(f"{path}: 'base' (path to base experiment YAML) is required")
    base_yaml = (path.parent / base).resolve() if not Path(base).is_absolute() else Path(base)
    if not base_yaml.exists():
        raise FileNotFoundError(f"base experiment YAML not found: {base_yaml}")

    cells_raw = raw.get("cells")
    if not cells_raw:
        raise ValueError(f"{path}: 'cells' must contain at least one cell")

    cells = []
    for c in cells_raw:
        cells.append(Cell(
            id=str(c["id"]),
            overrides=dict(c.get("overrides", {})),
            inactive_devices=tuple(str(d) for d in c.get("inactive_devices", [])),
            duration_min=c.get("duration_min"),
            warmup_min=c.get("warmup_min"),
            cooldown_min=c.get("cooldown_min"),
        ))

    return Batch(
        name=name,
        description=description,
        base_yaml=base_yaml,
        runs=int(raw.get("runs", 1)),
        duration_min=float(raw.get("duration_min", 30)),
        warmup_min=float(raw.get("warmup_min", 5)),
        cooldown_min=float(raw.get("cooldown_min", 2)),
        reset_between_runs=bool(raw.get("reset_between_runs", True)),
        upload_between_cells=bool(raw.get("upload_between_cells", True)),
        cells=tuple(cells),
        warmup_run=bool(raw.get("warmup_run", False)),
        boot_verify_sec=int(raw.get("boot_verify_sec", 20)),
    )


def render_run_yaml(batch: Batch, cell: Cell, run_index: int, out_dir: Path) -> Path:
    """Build a per-run experiment YAML at `out_dir/config.yaml`.

    Starts from the batch's base YAML, merges cell.overrides into `defaults`,
    and sets per-device `node_active` based on cell.inactive_devices. All
    devices present in the base YAML are kept; inactive ones get
    `node_active: 0`, active ones get `node_active: 1`.
    """
    with batch.base_yaml.open() as f:
        config = yaml.safe_load(f)

    config = copy.deepcopy(config)
    config["experiment"] = f"{batch.name}-{cell.id}-r{run_index:02d}"
    config["description"] = (
        f"Auto-generated by run_batch.py from {batch.base_yaml.name} "
        f"(batch={batch.name}, cell={cell.id}, run={run_index})"
    )

    defaults = config.setdefault("defaults", {})
    for k, v in cell.overrides.items():
        defaults[k] = v

    # YAML loads `1484` and `3428` as ints; normalize all device keys to
    # upper-case strings so set membership against `inactive_devices` works.
    inactive = {str(d).upper() for d in cell.inactive_devices}
    devices = config.setdefault("devices", {})
    new_devices = {}
    for short_id, dev_cfg in devices.items():
        key = str(short_id).upper()
        if not isinstance(dev_cfg, dict):
            dev_cfg = {}
        dev_cfg["node_active"] = 0 if key in inactive else 1
        new_devices[key] = dev_cfg
    config["devices"] = new_devices

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "config.yaml"
    with out_path.open("w") as f:
        yaml.safe_dump(config, f, sort_keys=False)
    return out_path


def iter_runs(batch: Batch):
    """Yield (cell, run_index, is_first_of_cell) for every run in the batch."""
    for cell in batch.cells:
        for run_index in range(1, batch.runs + 1):
            yield cell, run_index, (run_index == 1)
