"""Harvest per-device configs from gateways into an experiment YAML."""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from datetime import date
from pathlib import Path
from typing import Any

import yaml

from common import EXPERIMENTS_DIR, HexInt, TestbedConf, load_testbed_conf
from schema import PARAMS, param_by_define


# Matches both legacy scripts:
#   sed -i -E 's|^#define NAME .*|#define NAME VALUE|' "$CONFIG_H"
# and scripts generated by configtool (which use ANSI-C quoting + [^\r]*):
#   sed -i -E $'s|^#define NAME [^\r]*|#define NAME VALUE|' "$CONFIG_H"
_SED_RE = re.compile(
    r"""sed\s+-i\s+(?:-E\s+)?\$?['"]
        s\|\^\#define\s+([A-Z0-9_]+)\s+(?:\.\*|\[\^.r\]\*|\[\^\\r\]\*)\|
        \#define\s+\1\s+([^|]*)\|['"]""",
    re.VERBOSE,
)
# Plain #define line in src/config.h (only matches top-level, single-space form).
_DEFINE_RE = re.compile(r"^\s*#define\s+([A-Z0-9_]+)\s+(.+?)\s*$")


def harvest(out_path: Path | None = None, experiment_name: str | None = None) -> Path:
    """Pull change-config-*.sh + src/config.h from every gateway, parse the
    effective value of every known parameter per device, and emit a YAML with
    shared values in `defaults` and device-specific overrides in `devices`."""
    conf = load_testbed_conf()
    today = date.today().isoformat()
    if out_path is None:
        EXPERIMENTS_DIR.mkdir(parents=True, exist_ok=True)
        out_path = EXPERIMENTS_DIR / f"baseline-{today}.yaml"
    if experiment_name is None:
        experiment_name = f"baseline-{today}"

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)

        # Group devices by gateway to minimise SSH round-trips.
        by_gw: dict[str, list[str]] = {}
        for device_id, gw in conf.devices:
            by_gw.setdefault(gw, []).append(device_id.rsplit("-", 1)[-1])

        # Per-gateway working dirs for pulled files.
        per_device_scripts: dict[str, Path] = {}
        per_gateway_configh: dict[str, Path] = {}

        for gw, short_ids in by_gw.items():
            gw_dir = tmpdir / gw
            gw_dir.mkdir()
            print(f"[{gw}] fetching from {conf.gw_ssh.get(gw, '?')}")
            _scp_from_gateway(conf, gw, short_ids, gw_dir)
            cfg = gw_dir / "config.h"
            if cfg.exists():
                per_gateway_configh[gw] = cfg
            for sid in short_ids:
                s = gw_dir / f"change-config-{sid}.sh"
                if s.exists():
                    per_device_scripts[sid] = s

        # Build per-device parameter dict.
        per_device: dict[str, dict[str, Any]] = {}
        for device_id, gw in conf.devices:
            sid = device_id.rsplit("-", 1)[-1]
            base = _parse_config_h(per_gateway_configh[gw]) if gw in per_gateway_configh else {}
            script = per_device_scripts.get(sid)
            overrides = _parse_change_config(script) if script else {}
            merged: dict[str, Any] = {}
            # Only keep parameters that are in our schema.
            for key, p in PARAMS.items():
                if key in overrides:
                    merged[key] = overrides[key]
                elif key in base:
                    merged[key] = base[key]
            per_device[sid] = merged

        _write_experiment(out_path, experiment_name, per_device)

    print(f"wrote {out_path}")
    return out_path


def _scp_from_gateway(conf: TestbedConf, gw: str, short_ids: list[str], dest: Path) -> None:
    """SCP `src/config.h` and every known `change-config-*.sh` from a gateway
    back into `dest`. Uses the same auth logic as deploy.sh."""
    host = conf.gw_ssh.get(gw)
    if not host:
        raise RuntimeError(f"{gw}: no SSH destination in testbed.conf")

    scp_cmd = ["scp"]
    ssh_cmd_prefix: list[str] = []
    if gw in conf.gw_key:
        scp_cmd += ["-i", conf.gw_key[gw]]
        ssh_cmd_prefix += ["-i", conf.gw_key[gw]]
    if gw in conf.gw_port:
        scp_cmd += ["-P", conf.gw_port[gw]]
        ssh_cmd_prefix += ["-p", conf.gw_port[gw]]
    for opt in conf.ssh_opts.split():
        scp_cmd += [opt]
        ssh_cmd_prefix += [opt]

    # If a password is set, wrap with sshpass. Mirrors deploy.sh behaviour.
    password_wrap: list[str] = []
    if gw in conf.gw_pass and not conf.gw_key.get(gw):
        if not shutil.which("sshpass"):
            raise RuntimeError(
                f"{gw}: password auth configured but sshpass is not installed. "
                f"Either install sshpass, switch to a key in GW_KEY, or clear GW_PASS[{gw}]."
            )
        password_wrap = ["sshpass", "-p", conf.gw_pass[gw]]

    # 1) src/config.h (once per gateway).
    remote_cfg = f"{host}:{conf.repo_path}/src/config.h"
    cmd = password_wrap + scp_cmd + [remote_cfg, str(dest / "config.h")]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(f"  [{gw}] WARN: scp config.h failed: {r.stderr.strip()}")

    # 2) change-config-*.sh for each expected device. Accept failure (script
    # might not exist yet for a particular device).
    for sid in short_ids:
        name = f"change-config-{sid}.sh"
        # Check repo root first, then scripts/testbed/ (both locations gw-upload.sh searches).
        for remote_dir in (conf.repo_path, f"{conf.repo_path}/scripts/testbed"):
            remote = f"{host}:{remote_dir}/{name}"
            cmd = password_wrap + scp_cmd + [remote, str(dest / name)]
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode == 0:
                break
        else:
            print(f"  [{gw}] note: no change-config-{sid}.sh found on gateway (checked both paths)")


def _parse_config_h(path: Path) -> dict[str, Any]:
    """Extract all known-param values from a src/config.h. Top-level lines only
    (does not descend into #ifdef blocks — for our schema, all params are
    top-level)."""
    out: dict[str, Any] = {}
    if not path.exists():
        return out
    with open(path) as f:
        for line in f:
            m = _DEFINE_RE.match(line)
            if not m:
                continue
            name, value = m.group(1), m.group(2)
            # Trim trailing line comments.
            value = re.split(r"\s+//", value, maxsplit=1)[0].strip()
            p = param_by_define(name)
            if p is None:
                continue
            try:
                parsed = p.parse_c(value)
                out[p.yaml_key] = HexInt(parsed) if p.kind == "hex16" else parsed
            except Exception:
                pass
    return out


def _parse_change_config(path: Path) -> dict[str, Any]:
    """Extract param overrides from a change-config-*.sh script by matching
    its sed lines against the generator's pattern."""
    out: dict[str, Any] = {}
    if not path.exists():
        return out
    with open(path) as f:
        for line in f:
            m = _SED_RE.search(line)
            if not m:
                continue
            name, value = m.group(1), m.group(2).strip()
            p = param_by_define(name)
            if p is None:
                continue
            try:
                parsed = p.parse_c(value)
                out[p.yaml_key] = HexInt(parsed) if p.kind == "hex16" else parsed
            except Exception:
                pass
    return out


def _write_experiment(out_path: Path, name: str, per_device: dict[str, dict[str, Any]]) -> None:
    """Split per-device params into `defaults` (values shared by all devices)
    and per-device overrides (values that differ from the default)."""
    # A value goes into defaults iff every device has it AND they all agree.
    common: dict[str, Any] = {}
    if per_device:
        first = next(iter(per_device.values()))
        for key, v in first.items():
            if all(other.get(key, object()) == v for other in per_device.values()):
                common[key] = v

    defaults = dict(sorted(common.items()))
    devices: dict[str, dict[str, Any]] = {}
    for sid in sorted(per_device):
        overrides = {k: v for k, v in per_device[sid].items() if common.get(k, object()) != v}
        devices[sid] = dict(sorted(overrides.items())) if overrides else {}

    doc = {
        "experiment": name,
        "description": f"Auto-generated snapshot on {date.today().isoformat()}",
        "defaults": defaults,
        "devices": devices,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)
